use_frameworks!

target 'KFImageViewer_Example' do
  pod 'KFImageViewer', :path => '../'
  pod "KFImageViewer/Kingfisher", :path => "../"

  target 'KFImageViewer_Tests' do
    inherit! :search_paths
  end
  
end
